//! MAC address → vendor, from the IEEE MA-L (OUI) registry.
//!
//! The table (`data/oui.tsv`, regenerated by `scripts/update-oui.sh`) is
//! embedded in the binary and parsed once, on first use, into a sorted
//! vector searched by binary search.
//!
//! Locally administered MACs (second-lowest bit of the first octet set) are
//! not vendor-assigned — that is what phones and laptops use for Wi-Fi
//! privacy — so they never map to a vendor.

use std::sync::OnceLock;

static TABLE_SRC: &str = include_str!("../data/oui.tsv");

/// (24-bit prefix, vendor), sorted by prefix.
fn table() -> &'static [(u32, &'static str)] {
    static TABLE: OnceLock<Vec<(u32, &'static str)>> = OnceLock::new();
    TABLE.get_or_init(|| {
        let mut v: Vec<(u32, &'static str)> = TABLE_SRC
            .lines()
            .filter_map(|line| {
                let (prefix, name) = line.split_once('\t')?;
                Some((u32::from_str_radix(prefix, 16).ok()?, name))
            })
            .collect();
        v.sort_unstable_by_key(|&(p, _)| p);
        v
    })
}

/// Parse "aa:bb:cc:dd:ee:ff" (or with `-`) into its six octets.
fn parse_mac(mac: &str) -> Option<[u8; 6]> {
    let mut out = [0u8; 6];
    let mut parts = mac.split([':', '-']);
    for o in &mut out {
        *o = u8::from_str_radix(parts.next()?, 16).ok()?;
    }
    parts.next().is_none().then_some(out)
}

/// True for a locally administered (randomized / private) MAC.
pub fn is_locally_administered(mac: &str) -> bool {
    parse_mac(mac).is_some_and(|m| m[0] & 0x02 != 0)
}

/// The registered vendor of `mac`, if its OUI is in the IEEE registry.
pub fn vendor(mac: &str) -> Option<&'static str> {
    let m = parse_mac(mac)?;
    if m[0] & 0x02 != 0 {
        return None;
    }
    let prefix = (m[0] as u32) << 16 | (m[1] as u32) << 8 | m[2] as u32;
    let t = table();
    t.binary_search_by_key(&prefix, |&(p, _)| p)
        .ok()
        .map(|i| t[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_prefixes_resolve() {
        assert_eq!(vendor("00:50:56:ba:22:1d"), Some("VMware, Inc."));
        assert_eq!(vendor("00-50-56-BA-22-1D"), Some("VMware, Inc."));
        assert!(vendor("00:00:00:00:00:01").is_some());
    }

    #[test]
    fn locally_administered_has_no_vendor() {
        // 0e:… has the local bit set (iOS/Android private Wi-Fi address).
        assert!(is_locally_administered("0e:ea:14:cd:4c:2a"));
        assert_eq!(vendor("0e:ea:14:cd:4c:2a"), None);
        assert!(!is_locally_administered("00:50:56:ba:22:1d"));
    }

    #[test]
    fn malformed_macs_rejected() {
        assert_eq!(vendor(""), None);
        assert_eq!(vendor("00:50:56"), None);
        assert_eq!(vendor("00:50:56:ba:22:1d:ff"), None);
        assert_eq!(vendor("zz:50:56:ba:22:1d"), None);
    }

    #[test]
    fn table_is_loaded_and_sorted() {
        let t = table();
        assert!(t.len() > 30_000);
        assert!(t.windows(2).all(|w| w[0].0 < w[1].0));
    }
}
